// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Service.api.Movie.DBConfig;

#nullable disable

namespace Service.api.Movie.Migrations
{
    [DbContext(typeof(DBMoviePlusContext))]
    partial class DBMoviePlusContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Service.api.Movie.Entities.EMovie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Awards")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("BoxOffice")
                        .HasColumnType("int");

                    b.Property<int>("Budget")
                        .HasColumnType("int");

                    b.Property<string>("Cast")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ImdbRating")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MetacriticRating")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Plot")
                        .IsRequired()
                        .HasColumnType("varchar(600)");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("ProductionCompany")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ReleaseDate")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RottenTomatoesRating")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.Property<string>("TrailerUrl")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.HasKey("Id");

                    b.ToTable("Movies", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
